/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpdatesRouteImport } from './routes/_app.updates'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNavigationRouteImport } from './routes/_app.navigation'
import { Route as AppMessengerRouteImport } from './routes/_app.messenger'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppLostFoundRouteImport } from './routes/_app.lost-found'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppEmergencyRouteImport } from './routes/_app.emergency'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClubsRouteImport } from './routes/_app.clubs'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNavigationRoute = AppNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AppRoute,
} as any)
const AppMessengerRoute = AppMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLostFoundRoute = AppLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/clubs': typeof AppClubsRoute
  '/dashboard': typeof AppDashboardRoute
  '/emergency': typeof AppEmergencyRoute
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/lost-found': typeof AppLostFoundRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messenger': typeof AppMessengerRoute
  '/navigation': typeof AppNavigationRoute
  '/profile': typeof AppProfileRoute
  '/updates': typeof AppUpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/clubs': typeof AppClubsRoute
  '/dashboard': typeof AppDashboardRoute
  '/emergency': typeof AppEmergencyRoute
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/lost-found': typeof AppLostFoundRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messenger': typeof AppMessengerRoute
  '/navigation': typeof AppNavigationRoute
  '/profile': typeof AppProfileRoute
  '/updates': typeof AppUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/clubs': typeof AppClubsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/lost-found': typeof AppLostFoundRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/messenger': typeof AppMessengerRoute
  '/_app/navigation': typeof AppNavigationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/updates': typeof AppUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/clubs'
    | '/dashboard'
    | '/emergency'
    | '/events'
    | '/feed'
    | '/lost-found'
    | '/marketplace'
    | '/messenger'
    | '/navigation'
    | '/profile'
    | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/clubs'
    | '/dashboard'
    | '/emergency'
    | '/events'
    | '/feed'
    | '/lost-found'
    | '/marketplace'
    | '/messenger'
    | '/navigation'
    | '/profile'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/clubs'
    | '/_app/dashboard'
    | '/_app/emergency'
    | '/_app/events'
    | '/_app/feed'
    | '/_app/lost-found'
    | '/_app/marketplace'
    | '/_app/messenger'
    | '/_app/navigation'
    | '/_app/profile'
    | '/_app/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/navigation': {
      id: '/_app/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof AppNavigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messenger': {
      id: '/_app/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AppMessengerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lost-found': {
      id: '/_app/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof AppLostFoundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clubs': {
      id: '/_app/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClubsRoute: typeof AppClubsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppLostFoundRoute: typeof AppLostFoundRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessengerRoute: typeof AppMessengerRoute
  AppNavigationRoute: typeof AppNavigationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClubsRoute: AppClubsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppEventsRoute: AppEventsRoute,
  AppFeedRoute: AppFeedRoute,
  AppLostFoundRoute: AppLostFoundRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessengerRoute: AppMessengerRoute,
  AppNavigationRoute: AppNavigationRoute,
  AppProfileRoute: AppProfileRoute,
  AppUpdatesRoute: AppUpdatesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
